In [3]:
import numpy as np
import pandas as pd
# CSV
path = '/content/Online_Retail.csv'
retail_data = pd.read_csv(path, encoding='latin1')

# EXCEL
#date_excel = pd.read_excel(path)

#JSON
#data_json = pd.read_json(path)

# Imprime la informacion de las primeras 5 filas

print(retail_data.head())
print(type(retail_data))

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

    InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/10 8:26       2.55     17850.0  United Kingdom
1  12/1/10 8:26       3.39     17850.0  United Kingdom
2  12/1/10 8:26       2.75     17850.0  United Kingdom
3  12/1/10 8:26       3.39     17850.0  United Kingdom
4  12/1/10 8:26       3.39     17850.0  United Kingdom
<class 'pandas.core.frame.DataFrame'>

In [4]:
# informacion general de la base de datos
print(retail_data.info)

<bound method DataFrame.info of        InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

          InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/10 8:26       2.55     17850.0  United Kingdom
1        12/1/10 8:26       3.39     17850.0  United Kingdom
2        12/1/10 8:26       2.75     17850.0  United Kingdom
3        12/1/10 8:26       3.39     17850.0  United Kingdom
4        12/1/10 8:26       3.39     17850.0  United Kingdom
...               ...        ...         ...             ...
541904  12/9/11 12:50       0.85     12680.0          France
541905  12/9/11 12:50       2.10     12680.0          France
541906  12/9/11 12:50       4.15     12680.0          France
541907  12/9/11 12:50       4.15     12680.0          France
541908  12/9/11 12:50       4.95     12680.0          France

[541909 rows x 8 columns]>

In [5]:
print(retail_data.describe())

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [7]:
#suma Total de datos null o vacios
retail_data.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
#Imprime la suma de datos duplicaods
retail_data.duplicated().sum()

np.int64(5268)

In [16]:
unique_values = {col:retail_data[col].unique() for col in retail_data.columns}
for col, values in unique_values.items():
  print(f"Columna {col}:Numero de Valores únicos {len(values)}")
  print(f"Primeros 10 valores únicos: {values[:10]}")
  print("-"*50)

Columna InvoiceNo:Numero de Valores únicos 25900
Primeros 10 valores únicos: ['536365' '536366' '536367' '536368' '536369' '536370' '536371' '536372'
 '536373' '536374']
--------------------------------------------------
Columna StockCode:Numero de Valores únicos 4070
Primeros 10 valores únicos: ['85123A' '71053' '84406B' '84029G' '84029E' '22752' '21730' '22633'
 '22632' '84879']
--------------------------------------------------
Columna Description:Numero de Valores únicos 4224
Primeros 10 valores únicos: ['WHITE HANGING HEART T-LIGHT HOLDER' 'WHITE METAL LANTERN'
 'CREAM CUPID HEARTS COAT HANGER' 'KNITTED UNION FLAG HOT WATER BOTTLE'
 'RED WOOLLY HOTTIE WHITE HEART.' 'SET 7 BABUSHKA NESTING BOXES'
 'GLASS STAR FROSTED T-LIGHT HOLDER' 'HAND WARMER UNION JACK'
 'HAND WARMER RED POLKA DOT' 'ASSORTED COLOUR BIRD ORNAMENT']
--------------------------------------------------
Columna Quantity:Numero de Valores únicos 722
Primeros 10 valores únicos: [ 6  8  2 32  3  4 24 12 48 18]
--------------------------------------------------
Columna InvoiceDate:Numero de Valores únicos 23260
Primeros 10 valores únicos: ['12/1/10 8:26' '12/1/10 8:28' '12/1/10 8:34' '12/1/10 8:35'
 '12/1/10 8:45' '12/1/10 9:00' '12/1/10 9:01' '12/1/10 9:02'
 '12/1/10 9:09' '12/1/10 9:32']
--------------------------------------------------
Columna UnitPrice:Numero de Valores únicos 1630
Primeros 10 valores únicos: [2.55 3.39 2.75 7.65 4.25 1.85 1.69 2.1  3.75 1.65]
--------------------------------------------------
Columna CustomerID:Numero de Valores únicos 4373
Primeros 10 valores únicos: [17850. 13047. 12583. 13748. 15100. 15291. 14688. 17809. 15311. 14527.]
--------------------------------------------------
Columna Country:Numero de Valores únicos 38
Primeros 10 valores únicos: ['United Kingdom' 'France' 'Australia' 'Netherlands' 'Germany' 'Norway'
 'EIRE' 'Switzerland' 'Spain' 'Poland']
--------------------------------------------------

In [17]:
data_cleaned = retail_data.drop_duplicates()
data_cleaned = data_cleaned.dropna(subset=["CustomerID"])

print(data_cleaned)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

          InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/10 8:26       2.55     17850.0  United Kingdom
1        12/1/10 8:26       3.39     17850.0  United Kingdom
2        12/1/10 8:26       2.75     17850.0  United Kingdom
3        12/1/10 8:26       3.39     17850.0  United Kingdom
4        12/1/10 8:26       3.39     17850.0  United Kingdom
...               ...        ...         ...             ...
541904  12/9/11 12:50       0.85     12680.0          France
541905  12/9/11 12:50       2.10     12680.0          France
541906  12/9/11 12:50       4.15     12680.0          France
541907  12/9/11 12:50       4.15     12680.0          France
541908  12/9/11 12:50       4.95     12680.0          France

[401604 rows x 8 columns]

In [18]:
#suma Total de datos null o vacios
data_cleaned.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [ ]:
# .isna() funcion para identificar celdas faltantes o vacias
missing_data = retail_data.isna()
print(missing_data.head())

   InvoiceNo  StockCode  Description  Quantity  InvoiceDate  UnitPrice  \
0      False      False        False     False        False      False
1      False      False        False     False        False      False
2      False      False        False     False        False      False
3      False      False        False     False        False      False
4      False      False        False     False        False      False

   CustomerID  Country
0       False    False
1       False    False
2       False    False
3       False    False
4       False    False

In [ ]:
# isna().sum() funciones para sumar las celdas faltantes por columna
missing_data_count = retail_data.isna().sum()
print(f"conteo de datos por columna:\n {missing_data_count}")

conteo de datos por columna:
 InvoiceNo          0
StockCode          0
Description      337
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID     38769
Country            1
dtype: int64

In [ ]:
# Eliminar filas de datos faltantes, dropna() funcion que elimina las filas de los datos faltantes
no_missing_data = retail_data.dropna()
print(no_missing_data)

      InvoiceNo StockCode                          Description  Quantity  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER       6.0
1        536365     71053                  WHITE METAL LANTERN       6.0
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER       8.0
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE       6.0
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.       6.0
...         ...       ...                                  ...       ...
38660    539593     22961               JAM MAKING SET PRINTED      24.0
38661    539594     22086      PAPER CHAIN KIT 50'S CHRISTMAS       40.0
38662    539594     22910    PAPER CHAIN KIT VINTAGE CHRISTMAS      40.0
38663    539594    18098C       PORCELAIN BUTTERFLY OIL BURNER       6.0
38664    539594     22699     ROSES REGENCY TEACUP AND SAUCER        6.0

          InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/10 8:26       2.55     17850.0  United Kingdom
1        12/1/10 8:26       3.39     17850.0  United Kingdom
2        12/1/10 8:26       2.75     17850.0  United Kingdom
3        12/1/10 8:26       3.39     17850.0  United Kingdom
4        12/1/10 8:26       3.39     17850.0  United Kingdom
...               ...        ...         ...             ...
38660  12/20/10 13:31       1.45     13319.0  United Kingdom
38661  12/20/10 13:31       2.55     17621.0  United Kingdom
38662  12/20/10 13:31       2.55     17621.0  United Kingdom
38663  12/20/10 13:31       2.95     17621.0  United Kingdom
38664  12/20/10 13:31       2.95     17621.0  United Kingdom

[25432 rows x 8 columns]

In [ ]:
# Eliminar las columnas de datos faltantes dropna(axis =1)

no_missing_columns = retail_data.dropna(axis=1)
print(no_missing_columns)

      InvoiceNo StockCode
0        536365    85123A
1        536365     71053
2        536365    84406B
3        536365    84029G
4        536365    84029E
...         ...       ...
38663    539594    18098C
38664    539594     22699
38665    539595     22646
38666    539595     22649
38667    539595     22651

[38668 rows x 2 columns]

In [ ]:
#Remplaza los valores restantes con ceros fillna(0)
# isna en este caso es cero dado que se llenaron las celdas vacias con ceros
retail_data_fill_zeros = retail_data.fillna(0)
retail_data_fill_zeros_count = retail_data_fill_zeros.isna().sum()
print(retail_data_fill_zeros_count)
#

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [ ]:
# Variable["Llave"].mean() devuelve la media de una columna

mean_unit_values = retail_data['UnitPrice'].mean()
print(mean_unit_values)
# rellena los valores faltantes con la media

retail_data_filled_mean =  retail_data['UnitPrice'].fillna(mean_unit_values)
print(retail_data_filled_mean)

5.195988838179239
0         2.55
1         3.39
2         2.75
3         3.39
4         3.39
          ...
117001    1.65
117002    0.21
117003    0.42
117004    2.55
117005    0.72
Name: UnitPrice, Length: 117006, dtype: float64

In [ ]:
# Eliminar filas de datos faltantes, dropna() funcion que elimina las filas de los datos faltantes
no_missing_data = retail_data.dropna(subset=["CustomerID", "InvoiceDate"], inplace =True)
print(no_missing_data)

None